version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-dollar-exchange
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./dados-mysql:/var/lib/mysql
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge